# Generated by Django 5.0.7 on 2024-08-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrafos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='parrafos_images/'),
        ),
    ]
