# Generated by Django 5.0.7 on 2024-08-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parrafos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CartaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cartas/')),
                ('indice', models.PositiveIntegerField()),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.carta')),
            ],
        ),
    ]
