# Generated by Django 5.0.7 on 2024-09-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carta_cartaimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_seccion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galeria_images/')),
                ('vista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.textos')),
            ],
        ),
    ]
