# Generated by Django 5.0.7 on 2024-09-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nosotros_nosotrosimagen_delete_galeriaimagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
