# Generated by Django 5.0.7 on 2024-09-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nosotros_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaimagen',
            name='carta',
        ),
        migrations.RemoveField(
            model_name='nosotrosimagen',
            name='seccion',
        ),
        migrations.CreateModel(
            name='ImagenAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='parrafos_imagenes_adicionales/')),
                ('indice', models.IntegerField(blank=True, null=True)),
                ('parrafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='core.parrafos')),
            ],
        ),
        migrations.DeleteModel(
            name='Carta',
        ),
        migrations.DeleteModel(
            name='CartaImagen',
        ),
        migrations.DeleteModel(
            name='Nosotros',
        ),
        migrations.DeleteModel(
            name='NosotrosImagen',
        ),
    ]
